[package]
name = "docker-nested-routing"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.5"
actix-files = "0.6.5"
serde = { version = "1.0.104", features = ["derive"] }
env_logger = "0.11"
log = "0"
